### ISSUE TITLE
Compilation error on CRA (react scripts v. 1.1.4)

### ISSUE THREAD

**Issue by helsi-pro** [vrizo/uibook#10]
Hi, we have problem with compilation in project based on old CRA (on new project with updated CRA it does not reproduce).  
Error looks like `TypeError: compilation.entrypoints.forEach is not a function`
I`ve created PR to you with fix this bug #9

**Comment by vrizo** [comment]
Hi, @helsi-pro ! Thanks for the issue and PR!

Your fix is released in 0.5.7, please check.

Thank you!
